# Generated by Django 3.0.2 on 2020-11-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaProduk', models.CharField(max_length=200)),
                ('Golongan', models.CharField(choices=[('Gol Sosial 1A', 'Gol Sosial 1A'), ('Gol Sosial 1B', 'Gol Sosial 1B'), ('Gol Rumah Tangga 2A1', 'Gol Rumah Tangga 2A1'), ('Gol Rumah Tangga 2A2', 'Gol Rumah Tangga 2A2'), ('Gol Rumah Tangga 2A3', 'Gol Rumah Tangga 2A3'), ('Gol Rumah Tangga 2A4', 'Gol Rumah Tangga 2A4'), ('Gol Rumah Tangga 2A4', 'Gol Rumah Tangga 2A4'), ('Gol Rumah Tangga 2B', 'Gol Rumah Tangga 2B'), ('Gol Rumah Tangga 3A', 'Gol Rumah Tangga 3A'), ('Gol Niaga 3A', 'Gol Niaga 3A'), ('Gol Niaga 3B', 'Gol Niaga 3B'), ('Gol Industri 4A', 'Gol Industri 4A'), ('Gol Industri 4B', 'Gol Industri 4B')], max_length=500)),
                ('Harga', models.FloatField(null=True)),
                ('Pemakaian', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.ManyToManyField(to='account.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('STATUS', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200)),
                ('note', models.CharField(max_length=1000)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Product')),
            ],
        ),
    ]
